services:
  django:
    container_name: ${PROJECT_NAME}-django
    build: .
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - ${DJANGO_PORT}
    ports:
      - ${DJANGO_PORT}:8000
