# Generated by Django 6.0.7 on 2026-08-06 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='description',
        ),
    ]
